import type { Equipment, Category } from "../types"

export const EQUIPMENT_INIT: Equipment[] = [
  {
    id: 1,
    name: "Cámara Sony A7 III",
    category: "cameras",
    available: true,
    maintenance: false,
    image:
      "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=600&h=400&fit=crop&auto=format",
    specs: "Full-frame 24.2MP · 4K · ISO 102400 · Montura E",
    maxDays: 4,
    code: "CAM-001",
    brand: "Sony",
    quantity: 3,
    available_count: 2,
    altaGama: true,
    sede: "Ushuaia",
    locker: 2,
    careRules: [
      "No exponer a temperaturas menores a -10°C ni mayores a 45°C.",
      "Utilizar siempre el parasol cuando la lente esté montada.",
      "No tocar el sensor. En caso de suciedad, informar al laboratorio.",
      "Guardar con la tapa de cuerpo y sin lente montada.",
    ],
    videoUrl: "https://www.youtube.com/watch?v=JLCGg0nArKQ",
  },
  {
    id: 2,
    name: "Canon EOS R6",
    category: "cameras",
    available: false,
    maintenance: true,
    image:
      "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=600&h=400&fit=crop&auto=format",
    specs: "Full-frame 20.1MP · 4K · IBIS · Montura RF",
    maxDays: 4,
    code: "CAM-002",
    brand: "Canon",
    quantity: 2,
    available_count: 0,
    sede: "Ushuaia",
    locker: 2,
    careRules: [
      "Proteger de humedad y polvo con la bolsa incluida.",
      "No retirar la batería mientras la cámara está encendida.",
      "Formatear la tarjeta SD en cámara antes de usar.",
    ],
  },
  {
    id: 3,
    name: "Panel LED Godox SL-150W",
    category: "lighting",
    available: true,
    maintenance: false,
    image:
      "https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?w=600&h=400&fit=crop&auto=format",
    specs: "150W · 5600K · CRI 96+ · Bowens Mount",
    maxDays: 4,
    code: "LUZ-003",
    brand: "Godox",
    quantity: 4,
    available_count: 3,
    sede: "Ushuaia",
    locker: 4,
    careRules: [
      "No cubrir el panel mientras está encendido — riesgo de sobrecalentamiento.",
      "Dejar enfriar al menos 10 minutos antes de guardar.",
      "Transportar siempre en el maletín rígido asignado.",
    ],
    videoUrl: "https://www.youtube.com/watch?v=QDPF0kMgLcM",
  },
  {
    id: 4,
    name: "Micrófono Rode NTG5",
    category: "audio",
    available: true,
    maintenance: false,
    image:
      "https://images.unsplash.com/photo-1593078166039-c9878df5c520?w=600&h=400&fit=crop&auto=format",
    specs: "Shotgun · Supercardioide · XLR · 20Hz–20kHz",
    maxDays: 4,
    code: "AUD-007",
    brand: "Rode",
    quantity: 5,
    available_count: 4,
    sede: "Río Grande",
    locker: 5,
    careRules: [
      "No conectar/desconectar con phantom power activo.",
      "Guardar con el cover de espuma montado.",
      "Evitar golpes directos — la cápsula es frágil.",
    ],
  },
  {
    id: 5,
    name: 'MacBook Pro 14" M3',
    category: "computers",
    available: true,
    maintenance: false,
    image:
      "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=600&h=400&fit=crop&auto=format",
    specs: "Apple M3 Pro · 18GB RAM · 512GB SSD · macOS Sequoia",
    maxDays: 15,
    code: "PC-012",
    brand: "Apple",
    quantity: 8,
    available_count: 5,
    altaGama: true,
    sede: "Ushuaia",
    locker: 7,
    careRules: [
      "No instalar software sin autorización del laboratorio.",
      "Eliminar todos los archivos personales antes de devolver.",
      "No dejar cargando desatendido por más de 2 horas.",
      "Reportar cualquier falla en pantalla o teclado inmediatamente.",
    ],
    videoUrl: "https://www.youtube.com/watch?v=2fGEQdPKJfw",
  },
  {
    id: 6,
    name: "Softbox Neewer 90×120cm",
    category: "lighting",
    available: false,
    maintenance: true,
    image:
      "https://images.unsplash.com/photo-1574717025058-2f8737d2e2b7?w=600&h=400&fit=crop&auto=format",
    specs: "Octagonal · Bowens · Difusor doble capa · Plegable",
    maxDays: 4,
    code: "LUZ-005",
    brand: "Neewer",
    quantity: 6,
    available_count: 0,
    sede: "Río Grande",
    locker: 4,
    careRules: [
      "Plegar con cuidado siguiendo el diagrama impreso en la bolsa.",
      "No mojar el difusor de tela — lavado no autorizado.",
    ],
  },
  {
    id: 7,
    name: "Grabadora Zoom H6",
    category: "audio",
    available: true,
    maintenance: false,
    image:
      "https://images.unsplash.com/photo-1478737270239-2f02b77fc618?w=600&h=400&fit=crop&auto=format",
    specs: "6 pistas · WAV/MP3 · Preamps XLR · 96kHz/24bit",
    maxDays: 4,
    code: "AUD-011",
    brand: "Zoom",
    quantity: 3,
    available_count: 2,
    sede: "Río Grande",
    locker: 5,
    careRules: [
      "Retirar las pilas AA si no se va a usar por más de 48 horas.",
      "No doblar los cables XLR en ángulo menor a 90°.",
    ],
  },
  {
    id: 8,
    name: 'iPad Pro 12.9" M2',
    category: "computers",
    available: true,
    maintenance: false,
    image:
      "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=600&h=400&fit=crop&auto=format",
    specs: "Apple M2 · 256GB · Wi-Fi · Apple Pencil compatible",
    maxDays: 15,
    code: "PC-015",
    brand: "Apple",
    quantity: 6,
    available_count: 3,
    sede: "Ushuaia",
    locker: 7,
    careRules: [
      "Usar siempre con el Smart Folio cerrado para transporte.",
      "No apoyar objetos sobre la pantalla.",
      "Desloguear cuenta Apple al devolver.",
    ],
  },
]

export const CATEGORY_INIT: Category[] = [
  { id: "cameras", label: "Cámaras", color: "#1A4A7A" },
  { id: "lighting", label: "Iluminación", color: "#A0620D" },
  { id: "audio", label: "Audio", color: "#1A7A4A" },
  { id: "computers", label: "Computadoras", color: "#6E6E73" },
]
